version: '3.8'

services:
  web:
    image: myapp:latest
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://user:password@hostname:5432/mydb
    networks:
      - webnet

networks:
  webnet: