name: Container Scan

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t myapp:${{ github.sha }}

    - name: Run container scan
      uses: aquasecurity/trivy-action@v0.2.0
      with:
        image-ref: 'myapp:${{ github.sha }}'