name: Dependency Check

on: [push]

jobs:
  dependency:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run dependency check
      run: npm audit